### ISSUE TITLE
StartSpanWithOptions is crashing when the sampling rate is set to a value greater than 1.0 (i.e. 1.1 onwards) for sampler-type= probabilistic

### ISSUE THREAD

**Issue by Pratik-Shah** [jaegertracing/jaeger-client-cpp#149]
When the sampling rate is set to a value greater than 1.0 (i.e. 1.1 onwards) for sampler-type= probabilistic, we are observing a crash (signal SIGSEGV, Segmentation fault)

#0 0x00007f4e9fa7df3d in jaegertracing::Tracer::StartSpanWithOptions(opentracing::v2::string_view, opentracing::v2::StartSpanOptions const&) const () from /usr/local/lib64/libjaegertracing.so.0

#1 0x00007f4ea0120b5f in opentracing::v2::Tracer::StartSpan (this=0x2dbe140, operation_name=..., option_list=...) at /usr/local/include/opentracing/tracer.h:98

versions used:
opentracing-cpp-1.5.0-1
jaeger-client-cpp-0.4.2-1

**Comment by yurishkuro** [comment]
sampling rate is a probability, why are you setting it > 1?

**Comment by Pratik-Shah** [comment]
@yurishkuro agree with you.
It so happened that while testing one of the member considered placing 100 in order to have 100% sampling. 
Looking at the code, if we provide a number > 1 it would take the minimum(number,1.0) .
That is the reason to post this as the tracer creation succeeded but the start span crashed.

**Comment by yurishkuro** [comment]
please consider providing a PR to fix

**Comment by mdouaihy** [comment]
Hi @Pratik-Shah, implementations in other languages (Java and Go) have the same behavior: When a probabilistic sampler is requested with a probability not in the range [0, 1], an error occurs.

I think that this is the correct behavior. What does it mean to have a probability bigger than 1? it's a bug in the caller: Either it's failing to produce the correct probability or it's not respecting the contract of the sampler.

I think that make_sampler should throw an exception here instead of returning a nullptr as a sampler.

@yurishkuro, what do you think?

**Comment by yurishkuro** [comment]
Exception from sampler constructor sounds reasonable.
