### ISSUE TITLE
Why is spanId=0 not valid?

### ISSUE THREAD

**Issue by ramm** [jaegertracing/jaeger-client-cpp#182]
## Requirement - what kind of business use case are you trying to solve?

I'm trying to generate traceid from the outside of a blackbox application, that uses jaeger tracing cpp library. To achieve that I generate the fake `uber-trace-id` header with a traceid I want, and add zeroes for spanid and parentId. 

## Problem - what in Jaeger blocks you from solving the requirement?

https://github.com/jaegertracing/jaeger-client-cpp/blob/fec4327ba45c186a708879204e1466284a323104/src/jaegertracing/SpanContext.h#L153

This checks spanID to be not zero and considers my fake header not valid. Therefore — starts a new trace basically.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Remove spanID != 0 check.
Documentation (https://www.jaegertracing.io/docs/1.8/client-libraries/#value) does not declare it invalid (unlike traceid).
Also, some of the other client libraries do not have this check and therefore I can achieve my goal there.

**Comment by yurishkuro** [comment]
0 span ID is invalid. Jaeger libs never generate spanId==0. 

https://github.com/jaegertracing/jaeger-client-cpp/blob/5fc9c6507d2fd81ba72a0246a4d86ac654e88630/src/jaegertracing/Tracer.h#L248-L256

**Comment by ramm** [comment]
I do understand the concept. But Jaeger libs are not the one and only thing that MIGHT generate span context.

I'm not really sure, what exact problem does this solve.

What I'm trying to achieve is something like 
`proxy_set_header            uber-trace-id       $request_id:00000000:00000000:1;`
in nginx config.

This allow me to sync nginx request id and jaeger trace id throughout the whole setup of hundreds of service with a bunch of legacy code. This works ok for jaeger nodejs-client (it doesn't check for zero :)), but for cpp client in envoy — not so much.

I can change zeroes for something else, and everything kinda works, but I don't like "trace without root span" in Jaeger UI. 

So, if not by patching the client libs, what's the best way to achieve that?

**Comment by yurishkuro** [comment]
https://github.com/jaegertracing/jaeger-client-go/blob/master/context.go#L97
https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerSpanContext.java#L174

Both Java and Go clients consider span context invalid if it has 0 for trace or span IDs, meaning that the tracer will not use that span context as a parent (which is what you want), and therefore will generate a new trace ID (not what you want). So I think you stumbled on an inconsistency in the Node.js client that works in your favor, but was not intended for that.

I do find the idea interesting, using spanId=0 as "invalid as parent ID but do reuse the trace ID". But this would be a semantic change that should be coordinated across all clients. I am not convinced it is worth it, especially because it violates the rules of W3C Trace Context, which is currently compatible with the Jaeger's scheme.

By the way, there is a PR in `jaeger-ui` to avoid showing "trace without root span" - https://github.com/jaegertracing/jaeger-ui/pull/461

**Comment by ramm** [comment]
> By the way, there is a PR in jaeger-ui to avoid showing "trace without root span" - jaegertracing/jaeger-ui#461

this will probably fix my problem, thanks
