### ISSUE TITLE
make install doesn't install dependencies

### ISSUE THREAD

**Issue by xd009642** [jaegertracing/jaeger-client-cpp#216]
This may be more of a hunter issue but when I follow the install instructions in the readme and then try to add the project to another cmake project I get:

```
CMake Error at /usr/local/lib/cmake/jaegertracing/jaegertracingConfig.cmake:35 (find_package):
  Could not find a package configuration file provided by "thrift" with any
  of the following names:

    thriftConfig.cmake
    thrift-config.cmake

  Add the installation prefix of "thrift" to CMAKE_PREFIX_PATH or set
  "thrift_DIR" to a directory containing one of the above files.  If "thrift"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:140 (find_package)
```

is there a way to force the install of dependencies? Or do I need to download and install all of them myself separately to get this to work? And if so what's the purpose of hunter?

**Comment by james-ct** [comment]
Here because I want this exact same thing. The only reference I could find was this other issue (#44) which suggested the only way to actually use this library (without using hunter, I guess?) is to manually discover and install all the dependencies yourself, and hope that you've got compatible versions, I guess? Then disable hunter when you build this library?

I'm guessing because the proposed documentation additions either were never done or have since been removed, that conversation was 2.5 years ago...
