### ISSUE TITLE
debug error message in jaeger client while jaeger collector is not running

### ISSUE THREAD

**Issue by bcherukuri** [jaegertracing/jaeger-client-cpp#32]
Jaeger client constantly dumping following message when there is no jaeger collector running locally.

```
ERROR: Failed in Reporter::sweepQueue: Failed to write message, numWritten=-1, size=789: Connection refused, code=111
```

Is there any way to disable this?

**Comment by isaachier** [comment]
Not easily. Unfortunately, the error uses the `consoleLogger` to write this message so it doesn't matter if the logger is set to the `nullLogger`. I don't believe this is a major issue because you can always filter your logs using `grep -E -v 'Reporter::sweepQueue'`. Will leave open for future consideration.

**Comment by isaachier** [comment]
If you don't want tracing, just make `disabled = true` in the config.
